--Q35
SELECT DISTINCT LUONG
FROM GIAOVIEN
WHERE LUONG >= ALL(SELECT LUONG
					FROM GIAOVIEN)
--Q36
SELECT *
FROM GIAOVIEN
WHERE LUONG >= ALL(SELECT LUONG
					FROM GIAOVIEN)
--Q37
SELECT DISTINCT LUONG
FROM GIAOVIEN
WHERE MABM = 'HTTT' AND LUONG >= ALL(SELECT LUONG
										FROM GIAOVIEN
										WHERE MABM = 'HTTT')
--Q38
SELECT g.HOTEN
FROM GIAOVIEN g, BOMON b
WHERE g.MABM = b.MABM AND b.TENBM = N'Hệ thống thông tin' 
		AND g.NGSINH <= ALL(SELECT g.NGSINH
							FROM GIAOVIEN g, BOMON b
							WHERE g.MABM = b.MABM AND b.TENBM = N'Hệ thống thông tin')
--Q39
SELECT g.HOTEN
FROM GIAOVIEN g, BOMON b, KHOA k
WHERE g.MABM = b.MABM AND b.MAKHOA = k.MAKHOA AND k.TENKHOA = N'Công nghệ thông tin'
		AND g.NGSINH >= ALL(SELECT g.NGSINH
							FROM GIAOVIEN g, BOMON b, KHOA k
							WHERE g.MABM = b.MABM AND b.MAKHOA = k.MAKHOA AND k.TENKHOA = N'Công nghệ thông tin')
--Q40
SELECT g.HOTEN, k.TENKHOA
FROM GIAOVIEN g, BOMON b, KHOA k
WHERE g.MABM = b.MABM AND b.MAKHOA = k.MAKHOA
		AND g.LUONG >= ALL(SELECT g.LUONG
							FROM GIAOVIEN g)
--Q41
SELECT g.HOTEN, g.MABM
FROM GIAOVIEN g
WHERE g.LUONG >= ALL(SELECT g2.LUONG
					   FROM GIAOVIEN g2
					   WHERE g2.MABM = g.MABM)
--Q42
SELECT DISTINCT	d1.TENDT
FROM DETAI d1
WHERE NOT EXISTS(SELECT *
				 FROM GIAOVIEN g, THAMGIADT t, DETAI d2
				 WHERE g.HOTEN = N'Nguyễn Hoài An' AND g.MAGV = t.MAGV AND d2.MADT = t.MADT AND d1.MADT = d2.MADT)
--Q43
SELECT DISTINCT	d1.TENDT, g1.HOTEN as GVCNDT
FROM DETAI d1, GIAOVIEN g1
WHERE d1.GVCNDT = g1.MAGV
	AND NOT EXISTS(SELECT *
				   FROM GIAOVIEN g, THAMGIADT t, DETAI d2
				   WHERE g.HOTEN = N'Nguyễn Hoài An' AND g.MAGV = t.MAGV AND d2.MADT = t.MADT AND d1.MADT = d2.MADT)
--Q44
SELECT DISTINCT g.HOTEN
FROM GIAOVIEN g, BOMON b, KHOA k
WHERE g.MABM = b.MABM AND b.MAKHOA = k.MAKHOA AND k.TENKHOA = N'Công nghệ thông tin'
	AND NOT EXISTS(SELECT *
				   FROM THAMGIADT t
				   WHERE g.MAGV = t.MAGV)
--Q45
SELECT DISTINCT g.*
FROM GIAOVIEN g
WHERE NOT EXISTS(SELECT *
				 FROM THAMGIADT t
				 WHERE g.MAGV = t.MAGV)
--Q46
SELECT DISTINCT g.*
FROM GIAOVIEN g
WHERE g.LUONG > (SELECT LUONG
				 FROM GIAOVIEN
				 WHERE HOTEN = N'Nguyễn Hoài An')
--Q47
SELECT DISTINCT g.*
FROM GIAOVIEN g, BOMON b
WHERE b.TRUONGBM = g.MAGV
	AND EXISTS(SELECT *
			   FROM THAMGIADT t
			   WHERE g.MAGV = t.MAGV)
--Q48
SELECT DISTINCT g1.HOTEN
FROM GIAOVIEN g1, GIAOVIEN g2
WHERE g1.HOTEN = g2.HOTEN AND g1.PHAI = g2.PHAI AND g1.MABM = g2.MABM AND g1.MAGV != g2.MAGV

--Q49
SELECT DISTINCT g.HOTEN
FROM GIAOVIEN g
WHERE EXISTS(SELECT *
			 FROM GIAOVIEN g1, BOMON b
			 WHERE g1.MABM = b.MABM AND b.TENBM = N'Công nghệ phần mềm' AND g.LUONG > g1.LUONG)
--Q50
SELECT DISTINCT g.HOTEN
FROM GIAOVIEN g
WHERE g.LUONG > ALL(SELECT MAX(g1.LUONG)
					 FROM GIAOVIEN g1, BOMON b
					 WHERE g1.MABM = b.MABM AND b.TENBM = N'Hệ thống thông tin')
--Q51
SELECT k.TENKHOA
FROM GIAOVIEN g, KHOA k, BOMON b
WHERE g.MABM = b.MABM AND b.MAKHOA = k.MAKHOA
GROUP BY k.MAKHOA, k.TENKHOA
HAVING COUNT(g.MAGV) >= ALL(SELECT COUNT(g.MAGV)
							FROM GIAOVIEN g, KHOA k, BOMON b
							WHERE g.MABM = b.MABM AND b.MAKHOA = k.MAKHOA
							GROUP BY k.MAKHOA) 
--Q52
SELECT g.HOTEN
FROM GIAOVIEN g, DETAI d
WHERE g.MAGV = d.GVCNDT
GROUP BY g.MAGV, g.HOTEN
HAVING COUNT(*) >= ALL(SELECT COUNT(*)
					   FROM GIAOVIEN g, DETAI d
					   WHERE g.MAGV = d.GVCNDT
					   GROUP BY g.MAGV)
--Q53
SELECT MABM
FROM GIAOVIEN
GROUP BY MABM
HAVING COUNT(*) >= ALL(SELECT COUNT(*)
					   FROM GIAOVIEN
					   GROUP BY MABM)
--Q54
SELECT g.HOTEN, b.TENBM
FROM GIAOVIEN g, THAMGIADT t, BOMON b
WHERE g.MAGV = t.MAGV AND g.MABM = b.MABM
GROUP BY g.HOTEN, b.TENBM
HAVING COUNT(*) >= ALL(SELECT COUNT(*)
					   FROM GIAOVIEN g, THAMGIADT t
					   WHERE g.MAGV = t.MAGV
                       GROUP BY g.HOTEN)
--Q55
SELECT g.HOTEN
FROM GIAOVIEN g, THAMGIADT t
WHERE g.MAGV = t.MAGV AND g.MABM = 'HTTT'
GROUP BY g.HOTEN
HAVING COUNT(*) >= ALL(SELECT COUNT(*)
					   FROM GIAOVIEN g, THAMGIADT t
					   WHERE g.MAGV = t.MAGV AND g.MABM = 'HTTT'
                       GROUP BY g.HOTEN)
--Q56
SELECT g.HOTEN
FROM GIAOVIEN g, NGUOITHAN n, BOMON b
WHERE g.MAGV = n.MAGV AND g.MABM = b.MABM
GROUP BY g.HOTEN
HAVING COUNT(*) >= ALL(SELECT COUNT(*)
					   FROM GIAOVIEN g, NGUOITHAN n, BOMON b
					   WHERE g.MAGV = n.MAGV AND g.MABM = b.MABM
                       GROUP BY g.HOTEN)
--Q57
SELECT g.HOTEN
FROM GIAOVIEN g, DETAI d, BOMON b
WHERE g.MAGV = b.TRUONGBM AND g.MAGV = d.GVCNDT
GROUP BY g.HOTEN
HAVING COUNT(*) >= ALL(SELECT COUNT(*)
					   FROM GIAOVIEN g, DETAI d, BOMON b
					   WHERE g.MAGV = b.TRUONGBM AND g.MAGV = d.GVCNDT
					   GROUP BY g.HOTEN)